### PR TITLE
gossip ClusterState to root manager on join/remove

### LINKED ISSUE #12: Update  cluster state as soon as possible
In a few situations, such as join, creating ensembles, and ensemble membership change, the change can be committed to the root ensemble, but not immediately visible to the manager on the root leader. The root waits for the next tick before it gossips the new cluster state to the manager.  This can lead to situations where `riak_ensemble_peer:update_members/3` will return an error saying it isn't ready even though the nodes were already joined. This can be fixed to be 'synchronous' to the user by adding a call to `riak_ensemble_manager:gossip(State2)` before this line (for the join case): https://github.com/basho/riak_ensemble/blob/jdb-ensemble-overhaul/src/riak_ensemble_root.erl#L113

Note that this is NOT a bug. KV operations are still available at this time. This is simply an optimization to speed up membership changes and prevent rejecting them temporarily due to stale cluster state. Additionally, this all happens behind the scenes to the riak user. Joins and view membership are managed by riak and retries are made by riak, so the user is not affected by this.

I discussed this all with @jtuple and we agree that we will fix this before RC most likely, but it isn't critical.

### PR DESCRIPTION
**Pull request by andrewjstone**
When a node is newly joined, it is likely ensembles will be manipulated
on the newly joined node. However, future ensemble ops will fail until
the newly joined cluster member has been learned by the root manager on
the next tick. These changes ensure that the gossip happens immediately
on join and remove and prevents spurious errors relating to asynch
gossip, that must be retried. It is just an optimization.

Fixes #12 for join/remove case. Other cases were not changed as the
analysis seems less straightforward, and I'm not sure changes are even
required.

### CODE REVIEW

**Comment by engelsanchez** [comment]
I'm taking this review

**Comment by engelsanchez** [comment]
For the record, this is a fix for #29. The original #12 has been closed.

**Comment by engelsanchez** [comment]
@andrewjstone @jtuple This change will try to gossip a cluster state change in the precondition function of a modify operation in the root ensemble.  That means that we may be gossiping cluster state before we know if the put operation has been successful. That is, the call to gossip will happen [here](https://github.com/basho/riak_ensemble/blob/develop/src/riak_ensemble_peer.erl#L1416), but a few lines later putting that new cluster state with the added/removed node [may fail](https://github.com/basho/riak_ensemble/blob/develop/src/riak_ensemble_peer.erl#L1426).   I think for safety this needs to be changed to a root cast that will gossip the input to the precondition (a cluster state value that has been successfully written before).  What do you think?

**Comment by andrewjstone** [comment]
@engelsanchez You are absolutely right! Great Catch. This code is incorrect and dangerous. It will indeed gossip uncommitted cluster state which makes it unsafe.

After thinking about this for a while I think that I'd just rather not do this change at all. The impetus for it was some tests I was writing that joined nodes, got a success message, and then immediately tried to create ensembles containing the new nodes. However, this failed because the state had not been propogated to the manager yet because the leader tick hadn't fired yet and the gossip didn't occur. In riak, and smarter tests, the join will be done by a user, and the ensembles are automatically created without the user seeing any issues. Since node joins/removes are infrequent, and there'd still be a race if we sent another root cast (I think), I'd say we just leave things as they are and wait 2 seconds for the leader tick to propogate the new cluster state to the manager. If @engelsanchez @jtuple agree then this PR/issue can just be closed out.

**Comment by engelsanchez** [comment]
Ping. @andrewjstone @jtuple shall we close this now? I'm for that.

**Comment by andrewjstone** [comment]
Closing.

**Pull request closed without merging**
