### PR TITLE
Fix a dialyzer warning and enable warn_untyped_record

### PR DESCRIPTION
**Pull request by Vagabond**
Also, fixes a probable typo.

I didn't understand the purpose behind the maybe_drop, so I ifdefed it out in non-TEST mode.

I'm also not entirely sure that the {} instead of [] was a typo, but it sure looks like one.

cc @jtuple @andrewjstone

### CODE REVIEW

**Comment by andrewjstone** [comment]
Wow, good eye @Vagabond. I believe you did spot a typo. I also think the ifdef is correct for that function, but @jtuple would know for sure.

**Comment by cmeiklejohn** [comment]
Definitely a typo, if you look at how the state it used directly afterwards.  +1 efef53c

**Comment by Vagabond** [comment]
Merging, since @jtuple never chimed in.

**Comment by jtuple** [comment]
This was an outdated pull-request against code that has largely been re-written in #10. I was planning on re-evaluating these changes after that pull-request landed. But, looks like we've merged this and #10 doesn't merge cleanly now. Now we'll need to rebase that branch.

I didn't comment here earlier because I assumed everyone was letting me gatekeep `riak_ensemble` since we all know it's in considerable flux right now.

Please, no one else merge any other pull-request into `riak_ensemble` until I've explicitly signed off on them. I'm trying to minimize unnecessary future work given how much current, off-Github activity there is in-flight on this repository.

**Comment by Vagabond** [comment]
I'm fine with reverting the commit, or whatever. Please do try to be more explicit about 'do not merge' PRs though.

**Pull request merged**
