### PR TITLE
Change default for lease_duration config

### PR DESCRIPTION
**Pull request by andrewjstone**
Change the default to be `ensemble_tick * 2` instead of `ensemble_tick *
2 div 3`. The latter always results in a value smaller than the tick
timeout which would result in ticks firing after leases expired. Fix
this so that we properly use leases and maintain safety.

### CODE REVIEW

**Comment by andrewjstone** [comment]
It'd be interesting to add a test for this since it hasn't caused a problem yet in our tests AFAIK. It's probably still safe because of the long follower timeout.

**Comment by jtuple** [comment]
The initial value was a typo. It was supposed to be 1.5 times the ensemble tick, so `ensemble_tick * 3 div 2`. Oops. Any reason not to go with that vs `* 2`?

**Comment by andrewjstone** [comment]
@jtuple I just changed the value to `ensemble_tick * 3 div 2`, rebased and pushed.

**Comment by jtuple** [comment]
+1 d6556bf4430406efb698d0b1eed4c6dbcce530db

**Comment by jtuple** [comment]
Looks like Bors didn't actually merge this? Thus, didn't make it in for RC2?

**Comment by andrewjstone** [comment]
@borshop merge

**Comment by jtuple** [comment]
This change didn't make it into the 2.0 branch and wasn't part of RC2. Without this change, read leases can be invalid and lead to reads returning incorrect data. This is a super simple config-only change that doesn't invalidate any RC2 qualification/testing. Can we can merge this in for 2.0.0 final?
/cc @jaredmorrow @andrewjstone @jonmeredith @matthewvon

**Comment by jtuple** [comment]
Merged into 2.0 branch in e2ceebb37640c83a418648cbaeebce71e6b8f70b, will be in 2.0.0 final.

**Pull request merged**
