### PR TITLE
Fix root ensemble initial record

### PR DESCRIPTION
**Pull request by engelsanchez**
It seems to incorrectly store the version when {version, views} was
desired.

@jtuple I'm kind of guessing here since I'm not sure how to verify this.

### CODE REVIEW

**Comment by reiddraper** [comment]
Added 2.0-RC milestone. Feel free to remove if I've misunderstood.

**Comment by engelsanchez** [comment]
@reiddraper I'm just adding reminder PRs while I read the code that probably are not 2.0 blockers and probably are fixed in the current branches. I suppose there's a chance it's a real problem, but I don't know. Maybe let's leave that for @jtuple?

**Comment by reiddraper** [comment]
@engelsanchez sounds good. Just trying to keep the number of unassigned tickets low. But feel free to change as you all need.

**Comment by engelsanchez** [comment]
Ping @andrewjstone @jtuple shall we include this one liner fix? Have you had a minute to look at it?

**Comment by andrewjstone** [comment]
@engelsanchez Another great find! It looks like you are correct. I wonder what types of issue this was causing considering the data is used in `riak_ensemble_manager:get_views/1` and `get_members/1`. This is going to require a bit of testing.

**Comment by andrewjstone** [comment]
:+1:  b3634a8
All Ensemble riak_tests pass with this change.

**Comment by engelsanchez** [comment]
@borshop merge

**Pull request merged**
