### PR TITLE
Add replace_member test

### PR DESCRIPTION
**Pull request by andrewjstone**
Completely replace the root ensemble: root/2/3 -> 4/5/6
Since data doesn't sync anymore we will lose data, but it will be
detected instead of returning notfound.

### CODE REVIEW

**Comment by kellymclaughlin** [comment]
Output from review test run:

```
15:27:21:riak_ensemble(test/re-add-members *) $ ./rebar eunit apps=riak_ensemble suites=replace_members_test
==> riak_ensemble (eunit)
Compiled test/ens_test.erl
======================== EUnit ========================
module 'replace_members_test'
  replace_members_test: run_test_...test/replace_members_test.erl:19:<0.345.0>: Replacing Root Members: root/2/3 -> 4/5/6
test/replace_members_test.erl:22:<0.345.0>: Waiting for root ensemble to stabilize
test/replace_members_test.erl:25:<0.345.0>: Done waiting for root ensemble to stabilize
test/replace_members_test.erl:30:<0.345.0>: Performing failing get
test/replace_members_test.erl:35:<0.345.0>: Waiting for root ensemble to stabilize
test/replace_members_test.erl:38:<0.345.0>: Done waiting for root ensemble to stabilize
test/replace_members_test.erl:40:<0.345.0>: Replacing root members with original members
test/replace_members_test.erl:45:<0.345.0>: Waiting for root ensemble to stabilize
test/replace_members_test.erl:48:<0.345.0>: Done waiting for root ensemble to stabilize
test/replace_members_test.erl:51:<0.345.0>: Performing successful get
[20.361 s] ok
  [done in 20.364 s]
=======================================================
  Test passed.
```

**Comment by kellymclaughlin** [comment]
- [x] eunit tests
- [x] code review
- [x] dialyzer
- [x] xref

**Comment by andrewjstone** [comment]
Just squashed to 1 commit with a rebase.

**Comment by andrewjstone** [comment]
:+1: r=@kellymclaughlin

**Comment by andrewjstone** [comment]
:+1: 090e044

**Comment by andrewjstone** [comment]
@borshop merge

**Pull request merged**
