### PR TITLE
Add handle_down/4 cb for backend behavior

### PR DESCRIPTION
**Pull request by andrewjstone**
Handle 'DOWN' messages in the peer and callback into the backend
handle_down/4 function.

Part of a fix for basho/riak_kv#985

### CODE REVIEW

**Comment by andrewjstone** [comment]
https://github.com/basho/riak_kv/pull/990 should be merged first, because otherwise Mod:handle_down/4 won't exist in riak_kv_ensemble_backend when called from riak_ensemble_peer.

**Comment by andrewjstone** [comment]
Test is here: basho/riak_test#645
Test requires this PR: basho/riak_kv#990

**Comment by lordnull** [comment]
:+1: 1464498

Code looks clean and readable, nicely documented callback. associated r_t passes with this (and related) change, fails without.

**Comment by andrewjstone** [comment]
@borshop merge

**Pull request merged**
