### PR TITLE
Address numerous issues identified during testing

### PR DESCRIPTION
**Pull request by jtuple**
This pull-request addresses numerous issues identified during testing. This includes bugs with stable leadership, cluster state propagation, ensemble membership/view changes, etc.

This is a massive pull-request with lots of intertwined changes. The goal was to do whatever necessary to make new `riak_tests` pass consistently, without non-deterministic failures.

To simplify review, I've separated this pull-request into logical commits with detailed commit messages. This is a review that is best reviewed commit by commit.

Please look at the various commit messages for additional information about the bugs this pull-request fixes, and how it does so.

All testing is currently via `riak_tests` which will be in a soon-to-be-pushed sibling pull-request. However, I have some eunit tests that I might end up pushing to this branch in the near future as well. Including a PULSE based test.

Future pull-request will focus on more documentation as necessary, but given that this is a major rewrite of large portions of `riak_ensemble`, I'd rather get this reviewed/tested and be certain we're not going to have any other significant changes.

This addresses issue #7 

Sibling pull-requests: basho/riak_core#566, basho/riak_kv#887, basho/riak_test#569

### CODE REVIEW

**Comment by andrewjstone** [comment]
- [x] dialyzer
- [x] manual testing
- [x] xref
- [x] code review
- [x] automated testing

**Comment by andrewjstone** [comment]
Very close to the proverbial plus one. I added statem functionality in place of my manual testing and pushed up what I have for automated testing [so far](https://github.com/basho/riak_ensemble/compare/jdb-ensemble-overhaul...ajs%2Fpr10-testing?expand=1). I'd like to add a bit more to this tomorrow (kupdate, crashes, partitions) and re-run it first, but things are looking good. It can always be expanded after beta also.

**Comment by andrewjstone** [comment]
My automated statem test tests basic put/get/update functionality. It's lacking delete and partition/crash testing. That can wait until after beta. It passed a lot of iterations tonight and is good enough for now. @jtuple pushed up a few riak_tests tonight that I will run in the morning. If those all pass, I will +1 this.

**Comment by andrewjstone** [comment]
:+1: 

Excellent work @jtuple

**Comment by jtuple** [comment]
There are still a few minor comments in this pull-request that deserve some more attention. I'll work on converting those into issues against 2.0 RC. Thanks for the review @andrewjstone!

**Pull request merged**
