### PR TITLE
Add debug log messages for peer state transitions

### PR DESCRIPTION
**Pull request by nickelization**
This is fairly necessary to be able to debug issues with ensembles failing to stabilize, which is something we've seen in testing in the past.

### CODE REVIEW

**Comment by hazen** [comment]
:+1: fe59277

**Comment by nickelization** [comment]
I think we got hit by the "Bors doesn't like emoji" bug. Will try +1ing again...

**Comment by nickelization** [comment]
:+1: fe59277

**Comment by nickelization** [comment]
+1 fe59277

**Comment by nickelization** [comment]
Or maybe Bors is just dead. Guess I'll go ahead and merge manually.

**Pull request merged**
